CREATE TABLE tb_csf(
    id INT PRIMARY KEY AUTO_INCREMENT,
    pohon_id INT NOT NULL,
    pernyataan_kondisi_strategis TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB;