CREATE TABLE tb_outcome (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pohon_id INT NOT NULL,
    faktor_outcome TEXT,
    data_terukur TEXT,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB;