CREATE TABLE tb_intermediate (
    id INT AUTO_INCREMENT PRIMARY KEY,
    pohon_id INT NOT NULL,
    faktor_outcome VARCHAR(255) NOT NULL,
    data_terukur VARCHAR(255) NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)ENGINE=InnoDB;