// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "http://swagger.io/terms/",
        "contact": {
            "name": "API Support",
            "url": "http://www.swagger.io/support",
            "email": "support@swagger.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/csf": {
            "post": {
                "description": "Create Csf",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Csf"
                ],
                "summary": "Create Csf",
                "parameters": [
                    {
                        "description": "Csf",
                        "name": "csf",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/web.CsfCreateRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/web.WebResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "web.AlasanKondisiCreateRequest": {
            "type": "object",
            "properties": {
                "alasan_kondisi_strategis": {
                    "type": "string"
                },
                "data_terukur": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.DataTerukurCreateRequest"
                    }
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "web.AlasanKondisiUpdateRequest": {
            "type": "object",
            "properties": {
                "alasan_kondisi_strategis": {
                    "type": "string"
                },
                "data_terukur": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.DataTerukurUpdateRequest"
                    }
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "web.CsfCreateRequest": {
            "type": "object",
            "required": [
                "pernyataan_kondisi_strategis",
                "pohon_id"
            ],
            "properties": {
                "alasan_kondisi": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.AlasanKondisiCreateRequest"
                    }
                },
                "pernyataan_kondisi_strategis": {
                    "type": "string"
                },
                "pohon_id": {
                    "type": "integer"
                }
            }
        },
        "web.CsfUpdateRequest": {
            "type": "object",
            "required": [
                "id",
                "pernyataan_kondisi_strategis",
                "pohon_id"
            ],
            "properties": {
                "alasan_kondisi": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/web.AlasanKondisiUpdateRequest"
                    }
                },
                "id": {
                    "type": "integer"
                },
                "pernyataan_kondisi_strategis": {
                    "type": "string"
                },
                "pohon_id": {
                    "type": "integer"
                }
            }
        },
        "web.DataTerukurCreateRequest": {
            "type": "object",
            "properties": {
                "data_terukur": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "web.DataTerukurUpdateRequest": {
            "type": "object",
            "properties": {
                "data_terukur": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                }
            }
        },
        "web.WebResponse": {
            "description": "Web Response",
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "data": {},
                "status": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "${HOST}:${PORT}",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Isu Strategis Pemda",
	Description:      "API For Isu Strategis Pemda",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
