basePath: /
definitions:
  web.AlasanKondisiCreateRequest:
    properties:
      alasan_kondisi_strategis:
        type: string
      data_terukur:
        items:
          $ref: '#/definitions/web.DataTerukurCreateRequest'
        type: array
      id:
        type: integer
    type: object
  web.AlasanKondisiUpdateRequest:
    properties:
      alasan_kondisi_strategis:
        type: string
      data_terukur:
        items:
          $ref: '#/definitions/web.DataTerukurUpdateRequest'
        type: array
      id:
        type: integer
    type: object
  web.CsfCreateRequest:
    properties:
      alasan_kondisi:
        items:
          $ref: '#/definitions/web.AlasanKondisiCreateRequest'
        type: array
      pernyataan_kondisi_strategis:
        type: string
      pohon_id:
        type: integer
    required:
    - pernyataan_kondisi_strategis
    - pohon_id
    type: object
  web.CsfUpdateRequest:
    properties:
      alasan_kondisi:
        items:
          $ref: '#/definitions/web.AlasanKondisiUpdateRequest'
        type: array
      id:
        type: integer
      pernyataan_kondisi_strategis:
        type: string
      pohon_id:
        type: integer
    required:
    - id
    - pernyataan_kondisi_strategis
    - pohon_id
    type: object
  web.DataTerukurCreateRequest:
    properties:
      data_terukur:
        type: string
      id:
        type: integer
    type: object
  web.DataTerukurUpdateRequest:
    properties:
      data_terukur:
        type: string
      id:
        type: integer
    type: object
  web.WebResponse:
    description: Web Response
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
host: ${HOST}:${PORT}
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API For Isu Strategis Pemda
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Isu Strategis Pemda
  version: "1.0"
paths:
  /csf:
    post:
      consumes:
      - application/json
      description: Create Csf
      parameters:
      - description: Csf
        in: body
        name: csf
        required: true
        schema:
          $ref: '#/definitions/web.CsfCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Create Csf
      tags:
      - Csf
swagger: "2.0"
