basePath: /
definitions:
  web.AlasanKondisiCreateRequest:
    properties:
      alasan_kondisi_strategis:
        type: string
      data_terukur:
        items:
          $ref: '#/definitions/web.DataTerukurCreateRequest'
        type: array
      id:
        type: integer
    type: object
  web.AlasanKondisiUpdateRequest:
    properties:
      alasan_kondisi_strategis:
        type: string
      data_terukur:
        items:
          $ref: '#/definitions/web.DataTerukurUpdateRequest'
        type: array
      id:
        type: integer
    type: object
  web.CsfCreateRequest:
    properties:
      alasan_kondisi:
        items:
          $ref: '#/definitions/web.AlasanKondisiCreateRequest'
        type: array
      pernyataan_kondisi_strategis:
        type: string
      pohon_id:
        type: integer
      tahun:
        type: string
    required:
    - pernyataan_kondisi_strategis
    - pohon_id
    - tahun
    type: object
  web.CsfUpdateRequest:
    properties:
      alasan_kondisi:
        items:
          $ref: '#/definitions/web.AlasanKondisiUpdateRequest'
        type: array
      id:
        type: integer
      pernyataan_kondisi_strategis:
        type: string
      pohon_id:
        type: integer
      tahun:
        type: string
    required:
    - id
    - pernyataan_kondisi_strategis
    - pohon_id
    - tahun
    type: object
  web.DataTerukurCreateRequest:
    properties:
      data_terukur:
        type: string
      id:
        type: integer
    type: object
  web.DataTerukurUpdateRequest:
    properties:
      data_terukur:
        type: string
      id:
        type: integer
    type: object
  web.IntermediateCreateRequest:
    properties:
      data_terukur:
        type: string
      faktor_outcome:
        type: string
      pohon_id:
        type: integer
      tahun:
        type: string
    required:
    - data_terukur
    - faktor_outcome
    - pohon_id
    - tahun
    type: object
  web.IntermediateUpdateRequest:
    properties:
      data_terukur:
        type: string
      faktor_outcome:
        type: string
      id:
        type: integer
      pohon_id:
        type: integer
      tahun:
        type: string
    required:
    - data_terukur
    - faktor_outcome
    - pohon_id
    - tahun
    type: object
  web.WebResponse:
    description: Web Response
    properties:
      code:
        type: integer
      data: {}
      status:
        type: string
    type: object
host: ${HOST}:${PORT}
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API For Isu Strategis Pemda
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: Isu Strategis Pemda
  version: "1.0"
paths:
  /csf:
    post:
      consumes:
      - application/json
      description: Create Csf
      parameters:
      - description: Csf
        in: body
        name: csf
        required: true
        schema:
          $ref: '#/definitions/web.CsfCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Create Csf
      tags:
      - Csf
  /csf/:csfId:
    put:
      consumes:
      - application/json
      description: Update Csf
      parameters:
      - description: Csf ID
        in: path
        name: id
        required: true
        type: integer
      - description: Csf
        in: body
        name: csf
        required: true
        schema:
          $ref: '#/definitions/web.CsfUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Update Csf
      tags:
      - Csf
  /csf/:idPohon:
    delete:
      consumes:
      - application/json
      description: Delete Csf
      parameters:
      - description: Csf ID
        in: path
        name: csfId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Delete Csf
      tags:
      - Csf
  /csf/:tahun:
    get:
      consumes:
      - application/json
      description: Find All Csf
      parameters:
      - description: Tahun
        in: path
        name: tahun
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Find All Csf
      tags:
      - Csf
  /csf/detail/:csfId:
    get:
      consumes:
      - application/json
      description: Find Csf By Id
      parameters:
      - description: Csf ID
        in: path
        name: csfId
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Find Csf By Id
      tags:
      - Csf
  /intermediate:
    post:
      consumes:
      - application/json
      description: Create Intermediate
      parameters:
      - description: Intermediate
        in: body
        name: intermediate
        required: true
        schema:
          $ref: '#/definitions/web.IntermediateCreateRequest'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/web.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Create Intermediate
      tags:
      - Intermediate
  /intermediate/:id:
    put:
      consumes:
      - application/json
      description: Update Intermediate
      parameters:
      - description: Intermediate ID
        in: path
        name: id
        required: true
        type: integer
      - description: Intermediate
        in: body
        name: intermediate
        required: true
        schema:
          $ref: '#/definitions/web.IntermediateUpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Update Intermediate
      tags:
      - Intermediate
  /intermediate/:pohon_id:
    delete:
      consumes:
      - application/json
      description: Delete Intermediate
      parameters:
      - description: Intermediate ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Delete Intermediate
      tags:
      - Intermediate
  /intermediate/:tahun:
    get:
      consumes:
      - application/json
      description: Find All Intermediate
      parameters:
      - description: Tahun
        in: path
        name: tahun
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Find All Intermediate
      tags:
      - Intermediate
  /intermediate/detail/:id:
    get:
      consumes:
      - application/json
      description: Find Intermediate By Id
      parameters:
      - description: Intermediate ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/web.WebResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/web.WebResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/web.WebResponse'
      summary: Find Intermediate By Id
      tags:
      - Intermediate
swagger: "2.0"
